version: '3.7'

services:
  elasticsearch:
    build: 
      context: .  # 현재 디렉토리에 있는 Dockerfile을 사용하여 빌드
      dockerfile: Dockerfile
    container_name: elasticsearch
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

volumes:
  esdata01:
    driver: local
