# Generated by Django 5.1.6 on 2025-03-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptnt_prdlst_crtr_cd', models.CharField(max_length=10)),
                ('prdlst_nm', models.TextField()),
                ('drug_cpnt_kor_nm', models.TextField()),
                ('drug_cpnt_eng_nm', models.TextField()),
                ('bssh_nm', models.TextField()),
                ('pthd_nm', models.TextField()),
                ('ptnt_reg_dt', models.DateTimeField(auto_now_add=True)),
                ('ptnt_no', models.CharField(max_length=20)),
            ],
        ),
    ]
